/**
 *
 */

#include "combofish_utils.hpp"
#include <algorithm>
#include <debug/assertions.h>
#include <string>

void backtrack(int &res, string &s, int start_idx) {
  // outln(start_idx, ">> backtrack");
  if (start_idx >= s.size())
    return;

  unordered_set<char> uset;
  // uset.insert(s[start_idx]);

  for (int i = start_idx; i < s.size(); i++) {
    char c = s[i];
    if (uset.empty()) {
      uset.insert(c);
      continue;
    }

    if (uset.find(c) != uset.end()) {
      res = std::max(res, i - start_idx);
      // out(i, "i");
      // outln(res, "res");
      backtrack(res, s, i);
      break;
    } else {
      uset.insert(c);
    }
  }

  int us = uset.size();
  res = std::max(res, us);
}

int main(int argc, char **argv) {
  string s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
             "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
             "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ abcdefghijklmnopqrstuvwxyzABCD";
  int res = 0;

  for (int i = 0; i < s.size(); i++)
    backtrack(res, s, i);

  //  out_vec(res);
  outln(res, "res");

  return 0;
}
