/**
 *
 */

#include "combofish_utils.hpp"
#include <algorithm>
#include <debug/assertions.h>
#include <string>

int main(int argc, char **argv) {
  string s =
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ abcdefghijklmnopqrstuvwxyzABCD";

  // string s = "abcabcbb";
  int res = 0;

  auto isDup = [](const string &item, int idx, int len) {
    cout << "Call isDup: " << idx << " len: " << len << endl;
    unordered_set<char> uset;
    for (int i = idx; i < idx + len; i++) {
      char c = item[i];
      if (uset.find(c) != uset.end())
        return true;
      else
        uset.insert(c);
    }
    return false;
  };

  auto findDupLength = [](const string &s, int idx) {
    unordered_set<char> uset;
    for (int i = idx; i < s.size(); i++)
      if (!uset.count(s[i]))
        uset.insert(s[i]);
      else
        return i - idx;

    return (int)s.size() - idx;
  };

  if (s.size() == 0)
    res = 0;

  res = 1;
  cout << "s: " << s << endl;

  for (int i = 0; i < s.size();) {
    int next_the_char_idx = findDupLength(s, i);
    // cout << "Call findDupLength with i: " << i
    //      << " length: " << next_the_char_idx << endl;

    if (next_the_char_idx < res) {
      ++i;
      continue;
    }
    
    bool status = isDup(s, i, next_the_char_idx);
    if (!status) {
      res = std::max(res, next_the_char_idx);
      // outln(res, "update res to");
    }
    ++i;
  }

  //  out_vec(res);
  outln(res, "res");

  return 0;
}
