/**
 *
 */

#include "combofish_utils.hpp"
#include <algorithm>
#include <debug/assertions.h>
#include <string>

int main(int argc, char **argv) {
  string s1 =
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
      "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"
      "\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ abcdefghijklmnopqrstuvwxyzABCD";

  string s = "";
  int res = 0;

  auto isDup = [](const string &item, int idx, int len) {
    cout << "Call isDup: " << idx << " len: " << len << endl;
    unordered_set<char> uset;
    for (int i = idx; i < idx + len; i++) {
      char c = item[i];
      if (uset.find(c) != uset.end())
        return true;
      else
        uset.insert(c);
    }
    return false;
  };

  auto findDupLength = [](const string &s, int idx) {
    char c = s[idx];
    for (int i = idx + 1; i < s.size(); i++) {
      if (s[i] == c)
        return i - idx;
    }
    return (int)s.size() - idx;
  };

  if (s.size() == 0)
    res = 0;

  res = 1;
  cout << "s: " << s << endl;

  for (int i = 0; i < s.size();) {
    int next_the_char_idx = findDupLength(s, i);
    out(i, "i");
    out(next_the_char_idx, "length");

    bool status = isDup(s, i, next_the_char_idx);
    if (!status) {
      res = std::max(res, next_the_char_idx);
      outln(res, "update res to");
    }
    ++i;
  }

  //  out_vec(res);
  outln(res, "res");

  return 0;
}
